const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const source = fs.readFileSync(path.join(__dirname, '../src/market-order.ts'), 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS } }).outputText;
const compiled = { exports: {} };
new Function('require', 'module', 'exports', js)(require, compiled, compiled.exports);
const order = compiled.exports;
const repo = (key) => ({ key, owner: key.split('/')[0], repo: key.split('/')[1], url: `https://github.com/${key}` });
const entry = (name, key, date, notes) => ({ id: name, name, section: '公开', repositories: key ? [repo(key)] : [], wikiUpdatedAt: date, compatibilityNotes: notes });

assert.equal(order.compatibilityFor('适配版本: 0.5.10', '0.5.10'), 'supported');
assert.equal(order.compatibilityFor('适配版本: 0.5.x', '0.5.10'), 'supported');
assert.equal(order.compatibilityFor('适配版本: 0.5.x', '0.6.10'), 'mismatch');
assert.equal(order.compatibilityFor('适配版本: 0.5.10', '0.5.10.12'), 'mismatch');
assert.equal(order.compatibilityFor('计划适配版本: 0.5.10', '0.5.10'), 'unknown');
assert.equal(order.compatibilityFor('May support DoL 0.5.10', '0.5.10'), 'unknown');
assert.equal(order.compatibilityFor('未测试适配版本: 0.5.10', '0.5.10'), 'unknown');
assert.equal(order.compatibilityFor('不再支持 DoL 0.5.10', '0.5.10'), 'mismatch');
assert.equal(order.compatibilityFor('要求游戏版本 >= 0.6 < 0.5', '0.5.10'), 'unknown');
assert.equal(order.compatibilityFor('要求游戏版本 >= 0.5.10；目前未适配游戏最新版本 0.5.10', '0.5.10'), 'unknown');
assert.equal(order.compatibilityFor('适配版本: 0.5.10', undefined), 'unknown');
assert.equal(order.compatibilityFor('要求游戏版本 >= 0.5.10 < 0.6.0', '0.5.10.12'), 'supported');
assert.equal(order.compatibilityFor('未适配游戏最新版本 0.5.10.12', '0.5.10.12'), 'mismatch');
assert.equal(order.compatibilityFor('未适配游戏最新版本 0.5.10.12', '0.5.9'), 'unknown');
assert.equal(order.compatibilityFor('版本 0.5.10', '0.5.10'), 'unknown');
assert.equal(order.compatibilityFor('适配版本: 0.5.10 或 0.5.11', '0.5.10'), 'unknown');
assert.equal(order.entryDate(entry('bad', 'a/b', '2026/2/31'), {}, new Map([['a/b', 1]])).timestamp, 0);
const shared = entry('shared', 'a/b', '2025/1/1', '适配版本: 0.5.10');
const single = entry('single', 'c/d', '2025/1/1', '适配版本: 0.5.10');
const releases = { 'a/b': [{ publishedAt: '2026-01-01T00:00:00Z', compatibilityNotes: '适配版本: 0.4.0' }], 'c/d': [{ publishedAt: '2026-02-01T00:00:00Z', compatibilityNotes: '适配版本: 0.5.10' }] };
assert.equal(order.entryCompatibility(shared, '0.5.10', releases, new Map([['a/b', 2]])), 'supported');
assert.equal(order.entryCompatibility(single, '0.5.10', releases, new Map([['c/d', 1]])), 'supported');
assert.equal(order.entryDate(single,releases,new Map([['c/d',1]])).label,'发布时间');
assert.equal(order.entryDate(shared,releases,new Map([['a/b',2]])).label,'Wiki 更新');
assert.deepEqual(order.sortEntries([entry('mismatch','','2027/1/1','适配版本: 0.4.0'),entry('unknown','','2026/1/1'),entry('supported','','2025/1/1','适配版本: 0.5.10')],'0.5.10',{}).map(e=>e.name),['supported','unknown','mismatch']);
const ties=[entry('a','','2026/1/1'),entry('b','','2026/1/1')];assert.deepEqual(order.sortEntries(ties,undefined,{}).map(e=>e.name),['a','b']);assert.notEqual(order.sortEntries(ties,undefined,{}),ties);
const sharedOther = entry('shared-other', 'a/b', '2024/1/1', '适配版本: 0.5.10');
const sorted = order.sortEntries([shared, single, entry('unknown', '', '2027/1/1'), sharedOther], '0.5.10', releases);
assert.deepEqual(sorted.map((item) => item.name), ['single', 'shared', 'shared-other', 'unknown']);
console.log('market-order: passed');
